env:
  GIT_COOKIES: "ENCRYPTED[5afb5738a75ba757f4e9ef65e39dbbab481992b3a473f5356e56be73f5a769cc0d478a9f198c01e2a748ed33ba5026ad]"
  WORKDIR: "/ci"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Builder"
  timeout_in: 120m
  container:
    image: ghcr.io/sushrut1101/docker:arch
    cpu: 8
    memory: 32G
  
  Load-Cc_background_script:
     - bash load_cc.sh
  
  Build_script:
     - bash build.sh
